### ISSUE TITLE
Global data Store and Sharing views data

### ISSUE THREAD

**Issue by gautamverma** [kubetz/modular-backbone#2]
I am using the structure for my application. But however i am not able to do these 2 things.

1) How to store data in this type of structure globally?
2) How to share the models/collection between views.

I have building a site with login support, so i am want to store some data of the user for the time he is logged in the website. I have tried using app using require but it is undefined, or even window object but the data is null in other view.

Secondly i have many drop-down in the application and most of them share the data right now i have pull the drop-down data for each page every-time, can't we have available for all views after 1 download.

**Comment by kubetz** [comment]
Sorry for no answer for a long time. Have been very busy.

I hope you find your answer somewhere else. In case your issue is still not solved maybe having a look [here](http://stackoverflow.com/questions/9916073/how-to-load-bootstrapped-models-in-backbone-js-while-using-amd-require-js/10288587#10288587) helps.
